# 2022-03-07 19:08:41.294122: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory2022-03-07 19:08:41.294171: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.2022-03-07 19:08:42.223531: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory2022-03-07 19:08:42.223596: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)2022-03-07 19:08:42.223620: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (devel): /proc/driver/nvidia/version does not exist2022-03-07 19:08:42.223893: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMATo enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.Traceback (most recent call last):  File "/media/ivysyn/tensorflow/synthesized/all-crashes/all/ParameterizedTruncatedNormal_67115e2e5702a66698b72bbd6423fcfd.py", line 12, in <module>    tf.raw_ops.ParameterizedTruncatedNormal(shape=shape, means=means, stdevs=stdevs, minvals=minvals, maxvals=maxvals, seed=seed, seed2=seed2)  File "/home/neo/.local/lib/python3.9/site-packages/tensorflow/python/util/tf_export.py", line 400, in wrapper    return f(**kwargs)  File "/home/neo/.local/lib/python3.9/site-packages/tensorflow/python/ops/gen_random_ops.py", line 151, in parameterized_truncated_normal    _ops.raise_from_not_ok_status(e, name)  File "/home/neo/.local/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 7186, in raise_from_not_ok_status    raise core._status_to_exception(e) from None  # pylint: disable=protected-accesstensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid parameters [Op:ParameterizedTruncatedNormal]

# ParameterizedTruncatedNormalOp

import tensorflow as tf

seed = 1618
seed2 = 0
shape = tf.constant(100000, shape=[1], dtype=tf.int32)
means = tf.constant(0, shape=[], dtype=tf.float32)
stdevs = tf.constant(0, shape=[], dtype=tf.float32)
minvals = tf.constant(0, shape=[], dtype=tf.float32)
maxvals = tf.constant(2, shape=[], dtype=tf.float32)
tf.raw_ops.ParameterizedTruncatedNormal(shape=shape, means=means, stdevs=stdevs, minvals=minvals, maxvals=maxvals, seed=seed, seed2=seed2)