# 2022-01-28 15:26:25.381541: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX512F FMATo enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.Traceback (most recent call last):  File "/media/fuzzing-pytorch/anaconda3/lib/python3.8/site-packages/tensorflow/python/ops/gen_boosted_trees_ops.py", line 1137, in boosted_trees_make_quantile_summaries    _result = pywrap_tfe.TFE_Py_FastPathExecute(tensorflow.python.eager.core._NotOkStatusException: InvalidArgumentError: Weights should be a single value or same size as features. [Op:BoostedTreesMakeQuantileSummaries]During handling of the above exception, another exception occurred:Traceback (most recent call last):  File "/media/mlfuzz/tensorflow/synthesized/last-run-all/all/BoostedTreesMakeQuantileSummaries_436e4a9ac93e7c4eaf4d6475f5bb1186.py", line 7, in <module>    tf.raw_ops.BoostedTreesMakeQuantileSummaries(float_values=float_values, example_weights=example_weights, epsilon=epsilon, name=name)  File "/media/fuzzing-pytorch/anaconda3/lib/python3.8/site-packages/tensorflow/python/util/tf_export.py", line 404, in wrapper    return f(**kwargs)  File "/media/fuzzing-pytorch/anaconda3/lib/python3.8/site-packages/tensorflow/python/ops/gen_boosted_trees_ops.py", line 1142, in boosted_trees_make_quantile_summaries    _ops.raise_from_not_ok_status(e, name)  File "/media/fuzzing-pytorch/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 6939, in raise_from_not_ok_status    message = e.message + (" name: " + name if name is not None else "")  File "/media/fuzzing-pytorch/anaconda3/lib/python3.8/site-packages/tensorflow/python/ops/math_ops.py", line 1399, in r_binary_op_wrapper    y, x = maybe_promote_tensors(y, x)  File "/media/fuzzing-pytorch/anaconda3/lib/python3.8/site-packages/tensorflow/python/ops/math_ops.py", line 1335, in maybe_promote_tensors    ops.convert_to_tensor(tensor, dtype, name="x"))  File "/media/fuzzing-pytorch/anaconda3/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py", line 163, in wrapped    return func(*args, **kwargs)  File "/media/fuzzing-pytorch/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1566, in convert_to_tensor    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)  File "/media/fuzzing-pytorch/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 346, in _constant_tensor_conversion_function    return constant(v, dtype=dtype, name=name)  File "/media/fuzzing-pytorch/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 271, in constant    return _constant_impl(value, dtype, shape, name, verify_shape=False,  File "/media/fuzzing-pytorch/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 283, in _constant_impl    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)  File "/media/fuzzing-pytorch/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 308, in _constant_eager_impl    t = convert_to_eager_tensor(value, ctx, dtype)  File "/media/fuzzing-pytorch/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 106, in convert_to_eager_tensor    return ops.EagerTensor(value, ctx.device_name, dtype)TypeError: Cannot convert ' name: ' to EagerTensor of dtype float

import tensorflow as tf

float_values = tf.constant(1.2, shape=[6], dtype=tf.float32)
example_weights = tf.constant(1.2, shape=[6], dtype=tf.float32)
epsilon = tf.constant(1.2, shape=[6], dtype=tf.float32)
name = tf.constant(1.2, shape=[6], dtype=tf.float32)
tf.raw_ops.BoostedTreesMakeQuantileSummaries(float_values=float_values, example_weights=example_weights, epsilon=epsilon, name=name)